/* oxlint-disable */
/* eslint-disable */
/// <reference types="@quasar/app-vite" />
/// <reference types="@quasar/app-vite/client" />

// https://quasar.dev/quasar-cli-vite/handling-import-meta-env#type-inference

// Automatically generated from raw build.define
declare const __VUE_PROD_DEVTOOLS__: boolean;
declare const __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: boolean;
declare const __VUE_I18N_FULL_INSTALL__: boolean;
declare const __VUE_I18N_LEGACY_API__: boolean;
declare const __VUE_I18N_PROD_DEVTOOLS__: boolean;
declare const __INTLIFY_PROD_DEVTOOLS__: boolean;
declare const __DEV__: boolean;
declare const __VUE_OPTIONS_API__: boolean;

// Automatically generated from process.env & dotenv files & build.define & build.defineEnv;
// Backend-only are not available in client code, so they are marked as optional
interface ImportMetaEnv {
  readonly SHELL?: string;
  readonly SESSION_MANAGER?: string;
  readonly WINDOWID?: number;
  readonly USER_ZDOTDIR?: string;
  readonly COLORTERM?: string;
  readonly XDG_CONFIG_DIRS?: string;
  readonly LESS?: string;
  readonly XDG_SESSION_PATH?: string;
  readonly NVM_INC?: string;
  readonly XDG_MENU_PREFIX?: string;
  readonly TERM_PROGRAM_VERSION?: string;
  readonly _P9K_TTY?: string;
  readonly VSSCRIPT_PATH?: string;
  readonly LESS_TERMCAP_se?: string;
  readonly LESS_TERMCAP_so?: string;
  readonly LC_ADDRESS?: string;
  readonly JAVA_HOME?: string;
  readonly LC_NAME?: string;
  readonly SSH_AUTH_SOCK?: string;
  readonly P9K_TTY?: string;
  readonly XDG_CONFIG_HOME?: string;
  readonly DESKTOP_SESSION?: string;
  readonly LC_MONETARY?: string;
  readonly SSH_AGENT_PID?: number;
  readonly NO_AT_BRIDGE?: number;
  readonly GTK_MODULES?: string;
  readonly XDG_SEAT?: string;
  readonly PWD?: string;
  readonly XDG_SESSION_DESKTOP?: string;
  readonly LOGNAME?: string;
  readonly XDG_SESSION_TYPE?: string;
  readonly PANEL_GDK_CORE_DEVICE_EVENTS?: number;
  readonly PNPM_HOME?: string;
  readonly XAUTHORITY?: string;
  readonly LS_OPTIONS?: string;
  readonly VSCODE_GIT_ASKPASS_NODE?: string;
  readonly XDG_GREETER_DATA_DIR?: string;
  readonly MOTD_SHOWN?: string;
  readonly VSCODE_INJECTION?: number;
  readonly GDM_LANG?: string;
  readonly HOME?: string;
  readonly LC_PAPER?: string;
  readonly LANG?: string;
  readonly LS_COLORS?: string;
  readonly XDG_CURRENT_DESKTOP?: string;
  readonly VTE_VERSION?: number;
  readonly GIT_ASKPASS?: string;
  readonly XDG_SEAT_PATH?: string;
  readonly CHROME_DESKTOP?: string;
  readonly XDG_CACHE_HOME?: string;
  readonly NVM_DIR?: string;
  readonly VSCODE_GIT_ASKPASS_EXTRA_ARGS?: string;
  readonly VSCODE_PYTHON_AUTOACTIVATE_GUARD?: number;
  readonly CLAUDE_CODE_SSE_PORT?: number;
  readonly XDG_SESSION_CLASS?: string;
  readonly ANDROID_AVD_HOME?: string;
  readonly ANDROID_HOME?: string;
  readonly TERM?: string;
  readonly LC_IDENTIFICATION?: string;
  readonly LESS_TERMCAP_mb?: string;
  readonly LESS_TERMCAP_me?: string;
  readonly LESS_TERMCAP_md?: string;
  readonly VSCODE_NONCE?: string;
  readonly ZDOTDIR?: string;
  readonly USER?: string;
  readonly VSCODE_GIT_IPC_HANDLE?: string;
  readonly DISPLAY?: string;
  readonly SHLVL?: number;
  readonly LESS_TERMCAP_ue?: string;
  readonly NVM_CD_FLAGS?: string;
  readonly LESS_TERMCAP_us?: string;
  readonly LC_TELEPHONE?: string;
  readonly ANDROID_SDK_ROOT?: string;
  readonly _P9K_SSH_TTY?: string;
  readonly LC_MEASUREMENT?: string;
  readonly XDG_VTNR?: number;
  readonly XDG_SESSION_ID?: number;
  readonly FC_FONTATIONS?: number;
  readonly XDG_RUNTIME_DIR?: string;
  readonly NODE_PATH?: string;
  readonly DEBUGINFOD_URLS?: string;
  readonly LC_TIME?: string;
  readonly BUN_INSTALL?: string;
  readonly P9K_SSH?: number;
  readonly VSCODE_GIT_ASKPASS_MAIN?: string;
  readonly XDG_DATA_DIRS?: string;
  readonly GDK_BACKEND?: string;
  readonly PATH?: string;
  readonly GDMSESSION?: string;
  readonly DBUS_SESSION_BUS_ADDRESS?: string;
  readonly NVM_BIN?: string;
  readonly MAIL?: string;
  readonly LC_NUMERIC?: string;
  readonly OLDPWD?: string;
  readonly TERM_PROGRAM?: string;
  readonly QUASAR_CLI_VERSION?: string;
  readonly NODE_ENV?: string;
  readonly ACCEPT_OAUTH?: string;
  readonly API_MAPS?: string;
  readonly APP_LOGO?: string;
  readonly APP_NAME?: string;
  readonly COOKIE_THEME_NAME?: string;
  readonly DECODE_PASS_KEY?: string;
  readonly ENV?: string;
  readonly GRAPHQL_APP?: string;
  readonly GRAPHQL_AUTH?: string;
  readonly GRAPHQL_SSE_APP?: string;
  readonly GRAPHQL_WSS?: string;
  readonly GRAPHQL_WSS_APP?: string;
  readonly KEEP_CLIMA?: string;
  readonly LAST_DARK_STATE?: string;
  readonly NOTIFICACIONES_SUBS?: string;
  readonly SHOW_DASH_APP?: string;
  readonly SHOW_DASH_REPORTE1?: string;
  readonly SHOW_DASH_REPORTE2?: string;
  readonly SHOW_LANDING_PAGE?: string;
  readonly SHOW_LOGIN_BUTTON?: string;
  readonly SHOW_ROL_SELECT?: string;
  readonly SHOW_TIME_LABEL?: string;
  readonly SHOW_TOUR_TUTO?: number;
  readonly SHOW_TUTO_VIDEO?: string;
  readonly TUTO_VIDEO_URL?: string;
  readonly XDATAUSER_NAME?: string;
  readonly XDATAUSER_ROLUNIDAD?: string;
  readonly XMENUS_NAME?: string;
  readonly XSESIONKEY_NAME?: string;
  readonly XSESION_LABEL?: string;
  readonly XSESION_TIME?: string;
  readonly XTHEMA_CUADERNO?: string;
  readonly X_CLIMA?: string;
}
